pipeline:
  clone:
    image: plugins/git
    depth: 1

  phpcs:
    image: composer:latest
    commands:
      - echo $(date)
      - composer install --prefer-dist --no-progress --no-interaction
      - vendor/bin/robo check:codestyle
      - echo $(date)
