language: php
sudo: false

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer install --prefer-dist --no-progress --no-interaction

script:
  - vendor/bin/robo check:codestyle
